# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: 'vs2017-win2016'

steps:

- task: PowerPlatformToolInstaller@0
  inputs:
    DefaultVersion: true

- task: PowerPlatformExportSolution@0
  inputs:
    authenticationType: 'PowerPlatformEnvironment'
    PowerPlatformEnvironment: 'TSIS 2.0 Dev'
    SolutionName: '$(SolutionName)'
    SolutionOutputFile: '$(Build.ArtifactStagingDirectory)\$(SolutionName).zip'
    ExportRelationshipRoles: true

- task: PowerPlatformUnpackSolution@0
  inputs:
    SolutionInputFile: '$(Build.ArtifactStagingDirectory)\$(SolutionName).zip'
    SolutionTargetFolder: '$(Build.SourcesDirectory)\$(SolutionName)'


- task: CmdLine@2
  inputs:
      script: |
        echo commit all changes
        git config user.email "nepasrepondre-noreply@tc.gc.ca"
        git config user.name "tc-buildbot"
        git checkout development
        git add --all
        git commit -m "$env:COMMITMESSAGE"
        echo push code to new repo 
        git  -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push origin development