# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - development
    exclude:
    - releases/old*
    - feature/*-working
  paths:
    include:
    - PassengerProtectProgram/*
    exclude:
    - Plugin/*
    - WebResources/*

pool:
  vmImage:  'vs2017-win2016'

steps:

- task: PowerPlatformToolInstaller@0
  inputs:
    DefaultVersion: true



- task: PowerPlatformExportSolution@0
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: 'TSIS 2.0 Dev'
    SolutionName: '$(SolutionName)'
    SolutionOutputFile: '$(Build.ArtifactStagingDirectory)\$(SolutionName)_managed.zip'
    Managed: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)\$(SolutionName)_managed.zip'
    artifact: 'drop'
    publishLocation: 'pipeline'


