# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerAppsToolInstaller@0
  inputs:
    DefaultVersion: true

- task: PowerAppsExportSolution@0
  inputs:
    authenticationType: 'PowerAppsEnvironment'
    PowerAppsEnvironment: 'TSIS 2.0 Dev'
    SolutionName: '$(SolutionName)'
    SolutionOutputFile: '$(Build.ArtifactStagingDirectory)\$(SolutionName).zip'

- task: PowerAppsUnpackSolution@0
  inputs:
    SolutionInputFile: '$(Build.ArtifactStagingDirectory)\$(SolutionName).zip'
    SolutionTargetFolder: '$(Build.SourcesDirectory)\$(SolutionName)'

- task: CmdLine@2
  inputs:
    script: |
      echo commit all changes
      git config user.email "stephen.mouland@tc.gc.ca"
      git config user.name "Automatic Build"
      git checkout master
      git add --all
      git commit -m "solution init"
      echo push code to new repo
      git  -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push origin master