interface ppp_AcquittalandCompliance_Base extends WebEntity {
  createdon?: Date | null;
  importsequencenumber?: number | null;
  modifiedon?: Date | null;
  overriddencreatedon?: Date | null;
  ppp_acquittalandcomplianceid?: string | null;
  ppp_eventdescription?: string | null;
  ppp_flightorigindate?: Date | null;
  ppp_flightoriginhour?: number | null;
  ppp_flightoriginminute?: number | null;
  ppp_flightorigintime?: Date | null;
  ppp_name?: string | null;
  ppp_noncompliancedescription1?: string | null;
  ppp_noncompliancedescription10?: string | null;
  ppp_noncompliancedescription2?: string | null;
  ppp_noncompliancedescription3?: string | null;
  ppp_noncompliancedescription4?: string | null;
  ppp_noncompliancedescription5?: string | null;
  ppp_noncompliancedescription6?: string | null;
  ppp_noncompliancedescription7?: string | null;
  ppp_noncompliancedescription8?: string | null;
  ppp_noncompliancedescription9?: string | null;
  ppp_numberofflightconnection?: number | null;
  ppp_numberofnoncompliance?: number | null;
  ppp_numberofpaxaffected1?: number | null;
  ppp_numberofpaxaffected10?: number | null;
  ppp_numberofpaxaffected2?: number | null;
  ppp_numberofpaxaffected3?: number | null;
  ppp_numberofpaxaffected4?: number | null;
  ppp_numberofpaxaffected5?: number | null;
  ppp_numberofpaxaffected6?: number | null;
  ppp_numberofpaxaffected7?: number | null;
  ppp_numberofpaxaffected8?: number | null;
  ppp_numberofpaxaffected9?: number | null;
  ppp_passengernoncompliancedescription1?: string | null;
  ppp_passengernoncompliancedescription10?: string | null;
  ppp_passengernoncompliancedescription2?: string | null;
  ppp_passengernoncompliancedescription3?: string | null;
  ppp_passengernoncompliancedescription4?: string | null;
  ppp_passengernoncompliancedescription5?: string | null;
  ppp_passengernoncompliancedescription6?: string | null;
  ppp_passengernoncompliancedescription7?: string | null;
  ppp_passengernoncompliancedescription8?: string | null;
  ppp_passengernoncompliancedescription9?: string | null;
  ppp_passengernumberofnoncompliance?: number | null;
  ppp_recordtype?: ppp_recordtype | null;
  ppp_ruleid1?: ppp_ruleid | null;
  ppp_ruleid10?: ppp_ruleid | null;
  ppp_ruleid2?: ppp_ruleid | null;
  ppp_ruleid3?: ppp_ruleid | null;
  ppp_ruleid4?: ppp_ruleid | null;
  ppp_ruleid5?: ppp_ruleid | null;
  ppp_ruleid6?: ppp_ruleid | null;
  ppp_ruleid7?: ppp_ruleid | null;
  ppp_ruleid8?: ppp_ruleid | null;
  ppp_ruleid9?: ppp_ruleid | null;
  ppp_tsisdescription1?: string | null;
  ppp_tsisdescription10?: string | null;
  ppp_tsisdescription2?: string | null;
  ppp_tsisdescription3?: string | null;
  ppp_tsisdescription4?: string | null;
  ppp_tsisdescription5?: string | null;
  ppp_tsisdescription6?: string | null;
  ppp_tsisdescription7?: string | null;
  ppp_tsisdescription8?: string | null;
  ppp_tsisdescription9?: string | null;
  ppp_typeofnoncompliance1?: ppp_typeofnoncompliance | null;
  ppp_typeofnoncompliance10?: ppp_typeofnoncompliance | null;
  ppp_typeofnoncompliance2?: ppp_typeofnoncompliance | null;
  ppp_typeofnoncompliance3?: ppp_typeofnoncompliance | null;
  ppp_typeofnoncompliance4?: ppp_typeofnoncompliance | null;
  ppp_typeofnoncompliance5?: ppp_typeofnoncompliance | null;
  ppp_typeofnoncompliance6?: ppp_typeofnoncompliance | null;
  ppp_typeofnoncompliance7?: ppp_typeofnoncompliance | null;
  ppp_typeofnoncompliance8?: ppp_typeofnoncompliance | null;
  ppp_typeofnoncompliance9?: ppp_typeofnoncompliance | null;
  statecode?: ppp_acquittalandcompliance_statecode | null;
  statuscode?: ppp_acquittalandcompliance_statuscode | null;
  timezoneruleversionnumber?: number | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface ppp_AcquittalandCompliance_Relationships {
  ppp_SATAReference?: ppp_Traveller_Result | null;
}
interface ppp_AcquittalandCompliance extends ppp_AcquittalandCompliance_Base, ppp_AcquittalandCompliance_Relationships {
  ownerid_bind$systemusers?: string | null;
  ownerid_bind$teams?: string | null;
  ppp_AirCarrier_bind$ovs_aircarriers?: string | null;
  ppp_FlightConnection10_bind$ovs_facilities?: string | null;
  ppp_FlightConnection1_bind$ovs_facilities?: string | null;
  ppp_FlightConnection2_bind$ovs_facilities?: string | null;
  ppp_FlightConnection3_bind$ovs_facilities?: string | null;
  ppp_FlightConnection4_bind$ovs_facilities?: string | null;
  ppp_FlightConnection5_bind$ovs_facilities?: string | null;
  ppp_FlightConnection6_bind$ovs_facilities?: string | null;
  ppp_FlightConnection7_bind$ovs_facilities?: string | null;
  ppp_FlightConnection8_bind$ovs_facilities?: string | null;
  ppp_FlightConnection9_bind$ovs_facilities?: string | null;
  ppp_FlightDestination_bind$ovs_facilities?: string | null;
  ppp_FlightOrigin_bind$ovs_facilities?: string | null;
  ppp_InspectorName_bind$ts_tripinspectors?: string | null;
  ppp_SATAReference_bind$ppp_travellers?: string | null;
}
interface ppp_AcquittalandCompliance_Create extends ppp_AcquittalandCompliance {
}
interface ppp_AcquittalandCompliance_Update extends ppp_AcquittalandCompliance {
}
interface ppp_AcquittalandCompliance_Select {
  createdby_guid: WebAttribute<ppp_AcquittalandCompliance_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<ppp_AcquittalandCompliance_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<ppp_AcquittalandCompliance_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  importsequencenumber: WebAttribute<ppp_AcquittalandCompliance_Select, { importsequencenumber: number | null }, {  }>;
  modifiedby_guid: WebAttribute<ppp_AcquittalandCompliance_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<ppp_AcquittalandCompliance_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<ppp_AcquittalandCompliance_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  overriddencreatedon: WebAttribute<ppp_AcquittalandCompliance_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<ppp_AcquittalandCompliance_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<ppp_AcquittalandCompliance_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<ppp_AcquittalandCompliance_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<ppp_AcquittalandCompliance_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  ppp_acquittalandcomplianceid: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_acquittalandcomplianceid: string | null }, {  }>;
  ppp_aircarrier_guid: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_aircarrier_guid: string | null }, { ppp_aircarrier_formatted?: string }>;
  ppp_eventdescription: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_eventdescription: string | null }, {  }>;
  ppp_flightconnection10_guid: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_flightconnection10_guid: string | null }, { ppp_flightconnection10_formatted?: string }>;
  ppp_flightconnection1_guid: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_flightconnection1_guid: string | null }, { ppp_flightconnection1_formatted?: string }>;
  ppp_flightconnection2_guid: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_flightconnection2_guid: string | null }, { ppp_flightconnection2_formatted?: string }>;
  ppp_flightconnection3_guid: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_flightconnection3_guid: string | null }, { ppp_flightconnection3_formatted?: string }>;
  ppp_flightconnection4_guid: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_flightconnection4_guid: string | null }, { ppp_flightconnection4_formatted?: string }>;
  ppp_flightconnection5_guid: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_flightconnection5_guid: string | null }, { ppp_flightconnection5_formatted?: string }>;
  ppp_flightconnection6_guid: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_flightconnection6_guid: string | null }, { ppp_flightconnection6_formatted?: string }>;
  ppp_flightconnection7_guid: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_flightconnection7_guid: string | null }, { ppp_flightconnection7_formatted?: string }>;
  ppp_flightconnection8_guid: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_flightconnection8_guid: string | null }, { ppp_flightconnection8_formatted?: string }>;
  ppp_flightconnection9_guid: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_flightconnection9_guid: string | null }, { ppp_flightconnection9_formatted?: string }>;
  ppp_flightdestination_guid: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_flightdestination_guid: string | null }, { ppp_flightdestination_formatted?: string }>;
  ppp_flightorigin_guid: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_flightorigin_guid: string | null }, { ppp_flightorigin_formatted?: string }>;
  ppp_flightorigindate: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_flightorigindate: Date | null }, { ppp_flightorigindate_formatted?: string }>;
  ppp_flightoriginhour: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_flightoriginhour: number | null }, {  }>;
  ppp_flightoriginminute: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_flightoriginminute: number | null }, {  }>;
  ppp_flightorigintime: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_flightorigintime: Date | null }, { ppp_flightorigintime_formatted?: string }>;
  ppp_inspectorname_guid: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_inspectorname_guid: string | null }, { ppp_inspectorname_formatted?: string }>;
  ppp_name: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_name: string | null }, {  }>;
  ppp_noncompliancedescription1: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_noncompliancedescription1: string | null }, {  }>;
  ppp_noncompliancedescription10: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_noncompliancedescription10: string | null }, {  }>;
  ppp_noncompliancedescription2: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_noncompliancedescription2: string | null }, {  }>;
  ppp_noncompliancedescription3: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_noncompliancedescription3: string | null }, {  }>;
  ppp_noncompliancedescription4: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_noncompliancedescription4: string | null }, {  }>;
  ppp_noncompliancedescription5: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_noncompliancedescription5: string | null }, {  }>;
  ppp_noncompliancedescription6: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_noncompliancedescription6: string | null }, {  }>;
  ppp_noncompliancedescription7: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_noncompliancedescription7: string | null }, {  }>;
  ppp_noncompliancedescription8: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_noncompliancedescription8: string | null }, {  }>;
  ppp_noncompliancedescription9: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_noncompliancedescription9: string | null }, {  }>;
  ppp_numberofflightconnection: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_numberofflightconnection: number | null }, {  }>;
  ppp_numberofnoncompliance: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_numberofnoncompliance: number | null }, {  }>;
  ppp_numberofpaxaffected1: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_numberofpaxaffected1: number | null }, {  }>;
  ppp_numberofpaxaffected10: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_numberofpaxaffected10: number | null }, {  }>;
  ppp_numberofpaxaffected2: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_numberofpaxaffected2: number | null }, {  }>;
  ppp_numberofpaxaffected3: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_numberofpaxaffected3: number | null }, {  }>;
  ppp_numberofpaxaffected4: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_numberofpaxaffected4: number | null }, {  }>;
  ppp_numberofpaxaffected5: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_numberofpaxaffected5: number | null }, {  }>;
  ppp_numberofpaxaffected6: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_numberofpaxaffected6: number | null }, {  }>;
  ppp_numberofpaxaffected7: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_numberofpaxaffected7: number | null }, {  }>;
  ppp_numberofpaxaffected8: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_numberofpaxaffected8: number | null }, {  }>;
  ppp_numberofpaxaffected9: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_numberofpaxaffected9: number | null }, {  }>;
  ppp_passengernoncompliancedescription1: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_passengernoncompliancedescription1: string | null }, {  }>;
  ppp_passengernoncompliancedescription10: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_passengernoncompliancedescription10: string | null }, {  }>;
  ppp_passengernoncompliancedescription2: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_passengernoncompliancedescription2: string | null }, {  }>;
  ppp_passengernoncompliancedescription3: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_passengernoncompliancedescription3: string | null }, {  }>;
  ppp_passengernoncompliancedescription4: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_passengernoncompliancedescription4: string | null }, {  }>;
  ppp_passengernoncompliancedescription5: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_passengernoncompliancedescription5: string | null }, {  }>;
  ppp_passengernoncompliancedescription6: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_passengernoncompliancedescription6: string | null }, {  }>;
  ppp_passengernoncompliancedescription7: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_passengernoncompliancedescription7: string | null }, {  }>;
  ppp_passengernoncompliancedescription8: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_passengernoncompliancedescription8: string | null }, {  }>;
  ppp_passengernoncompliancedescription9: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_passengernoncompliancedescription9: string | null }, {  }>;
  ppp_passengernumberofnoncompliance: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_passengernumberofnoncompliance: number | null }, {  }>;
  ppp_recordtype: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_recordtype: ppp_recordtype | null }, { ppp_recordtype_formatted?: string }>;
  ppp_ruleid1: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_ruleid1: ppp_ruleid | null }, { ppp_ruleid1_formatted?: string }>;
  ppp_ruleid10: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_ruleid10: ppp_ruleid | null }, { ppp_ruleid10_formatted?: string }>;
  ppp_ruleid2: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_ruleid2: ppp_ruleid | null }, { ppp_ruleid2_formatted?: string }>;
  ppp_ruleid3: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_ruleid3: ppp_ruleid | null }, { ppp_ruleid3_formatted?: string }>;
  ppp_ruleid4: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_ruleid4: ppp_ruleid | null }, { ppp_ruleid4_formatted?: string }>;
  ppp_ruleid5: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_ruleid5: ppp_ruleid | null }, { ppp_ruleid5_formatted?: string }>;
  ppp_ruleid6: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_ruleid6: ppp_ruleid | null }, { ppp_ruleid6_formatted?: string }>;
  ppp_ruleid7: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_ruleid7: ppp_ruleid | null }, { ppp_ruleid7_formatted?: string }>;
  ppp_ruleid8: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_ruleid8: ppp_ruleid | null }, { ppp_ruleid8_formatted?: string }>;
  ppp_ruleid9: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_ruleid9: ppp_ruleid | null }, { ppp_ruleid9_formatted?: string }>;
  ppp_satareference_guid: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_satareference_guid: string | null }, { ppp_satareference_formatted?: string }>;
  ppp_tsisdescription1: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_tsisdescription1: string | null }, {  }>;
  ppp_tsisdescription10: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_tsisdescription10: string | null }, {  }>;
  ppp_tsisdescription2: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_tsisdescription2: string | null }, {  }>;
  ppp_tsisdescription3: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_tsisdescription3: string | null }, {  }>;
  ppp_tsisdescription4: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_tsisdescription4: string | null }, {  }>;
  ppp_tsisdescription5: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_tsisdescription5: string | null }, {  }>;
  ppp_tsisdescription6: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_tsisdescription6: string | null }, {  }>;
  ppp_tsisdescription7: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_tsisdescription7: string | null }, {  }>;
  ppp_tsisdescription8: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_tsisdescription8: string | null }, {  }>;
  ppp_tsisdescription9: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_tsisdescription9: string | null }, {  }>;
  ppp_typeofnoncompliance1: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_typeofnoncompliance1: ppp_typeofnoncompliance | null }, { ppp_typeofnoncompliance1_formatted?: string }>;
  ppp_typeofnoncompliance10: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_typeofnoncompliance10: ppp_typeofnoncompliance | null }, { ppp_typeofnoncompliance10_formatted?: string }>;
  ppp_typeofnoncompliance2: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_typeofnoncompliance2: ppp_typeofnoncompliance | null }, { ppp_typeofnoncompliance2_formatted?: string }>;
  ppp_typeofnoncompliance3: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_typeofnoncompliance3: ppp_typeofnoncompliance | null }, { ppp_typeofnoncompliance3_formatted?: string }>;
  ppp_typeofnoncompliance4: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_typeofnoncompliance4: ppp_typeofnoncompliance | null }, { ppp_typeofnoncompliance4_formatted?: string }>;
  ppp_typeofnoncompliance5: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_typeofnoncompliance5: ppp_typeofnoncompliance | null }, { ppp_typeofnoncompliance5_formatted?: string }>;
  ppp_typeofnoncompliance6: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_typeofnoncompliance6: ppp_typeofnoncompliance | null }, { ppp_typeofnoncompliance6_formatted?: string }>;
  ppp_typeofnoncompliance7: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_typeofnoncompliance7: ppp_typeofnoncompliance | null }, { ppp_typeofnoncompliance7_formatted?: string }>;
  ppp_typeofnoncompliance8: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_typeofnoncompliance8: ppp_typeofnoncompliance | null }, { ppp_typeofnoncompliance8_formatted?: string }>;
  ppp_typeofnoncompliance9: WebAttribute<ppp_AcquittalandCompliance_Select, { ppp_typeofnoncompliance9: ppp_typeofnoncompliance | null }, { ppp_typeofnoncompliance9_formatted?: string }>;
  statecode: WebAttribute<ppp_AcquittalandCompliance_Select, { statecode: ppp_acquittalandcompliance_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<ppp_AcquittalandCompliance_Select, { statuscode: ppp_acquittalandcompliance_statuscode | null }, { statuscode_formatted?: string }>;
  timezoneruleversionnumber: WebAttribute<ppp_AcquittalandCompliance_Select, { timezoneruleversionnumber: number | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<ppp_AcquittalandCompliance_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<ppp_AcquittalandCompliance_Select, { versionnumber: number | null }, {  }>;
}
interface ppp_AcquittalandCompliance_Filter {
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  importsequencenumber: number;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  ppp_acquittalandcomplianceid: XQW.Guid;
  ppp_aircarrier_guid: XQW.Guid;
  ppp_eventdescription: string;
  ppp_flightconnection10_guid: XQW.Guid;
  ppp_flightconnection1_guid: XQW.Guid;
  ppp_flightconnection2_guid: XQW.Guid;
  ppp_flightconnection3_guid: XQW.Guid;
  ppp_flightconnection4_guid: XQW.Guid;
  ppp_flightconnection5_guid: XQW.Guid;
  ppp_flightconnection6_guid: XQW.Guid;
  ppp_flightconnection7_guid: XQW.Guid;
  ppp_flightconnection8_guid: XQW.Guid;
  ppp_flightconnection9_guid: XQW.Guid;
  ppp_flightdestination_guid: XQW.Guid;
  ppp_flightorigin_guid: XQW.Guid;
  ppp_flightorigindate: Date;
  ppp_flightoriginhour: number;
  ppp_flightoriginminute: number;
  ppp_flightorigintime: Date;
  ppp_inspectorname_guid: XQW.Guid;
  ppp_name: string;
  ppp_noncompliancedescription1: string;
  ppp_noncompliancedescription10: string;
  ppp_noncompliancedescription2: string;
  ppp_noncompliancedescription3: string;
  ppp_noncompliancedescription4: string;
  ppp_noncompliancedescription5: string;
  ppp_noncompliancedescription6: string;
  ppp_noncompliancedescription7: string;
  ppp_noncompliancedescription8: string;
  ppp_noncompliancedescription9: string;
  ppp_numberofflightconnection: number;
  ppp_numberofnoncompliance: number;
  ppp_numberofpaxaffected1: number;
  ppp_numberofpaxaffected10: number;
  ppp_numberofpaxaffected2: number;
  ppp_numberofpaxaffected3: number;
  ppp_numberofpaxaffected4: number;
  ppp_numberofpaxaffected5: number;
  ppp_numberofpaxaffected6: number;
  ppp_numberofpaxaffected7: number;
  ppp_numberofpaxaffected8: number;
  ppp_numberofpaxaffected9: number;
  ppp_passengernoncompliancedescription1: string;
  ppp_passengernoncompliancedescription10: string;
  ppp_passengernoncompliancedescription2: string;
  ppp_passengernoncompliancedescription3: string;
  ppp_passengernoncompliancedescription4: string;
  ppp_passengernoncompliancedescription5: string;
  ppp_passengernoncompliancedescription6: string;
  ppp_passengernoncompliancedescription7: string;
  ppp_passengernoncompliancedescription8: string;
  ppp_passengernoncompliancedescription9: string;
  ppp_passengernumberofnoncompliance: number;
  ppp_recordtype: ppp_recordtype;
  ppp_ruleid1: ppp_ruleid;
  ppp_ruleid10: ppp_ruleid;
  ppp_ruleid2: ppp_ruleid;
  ppp_ruleid3: ppp_ruleid;
  ppp_ruleid4: ppp_ruleid;
  ppp_ruleid5: ppp_ruleid;
  ppp_ruleid6: ppp_ruleid;
  ppp_ruleid7: ppp_ruleid;
  ppp_ruleid8: ppp_ruleid;
  ppp_ruleid9: ppp_ruleid;
  ppp_satareference_guid: XQW.Guid;
  ppp_tsisdescription1: string;
  ppp_tsisdescription10: string;
  ppp_tsisdescription2: string;
  ppp_tsisdescription3: string;
  ppp_tsisdescription4: string;
  ppp_tsisdescription5: string;
  ppp_tsisdescription6: string;
  ppp_tsisdescription7: string;
  ppp_tsisdescription8: string;
  ppp_tsisdescription9: string;
  ppp_typeofnoncompliance1: ppp_typeofnoncompliance;
  ppp_typeofnoncompliance10: ppp_typeofnoncompliance;
  ppp_typeofnoncompliance2: ppp_typeofnoncompliance;
  ppp_typeofnoncompliance3: ppp_typeofnoncompliance;
  ppp_typeofnoncompliance4: ppp_typeofnoncompliance;
  ppp_typeofnoncompliance5: ppp_typeofnoncompliance;
  ppp_typeofnoncompliance6: ppp_typeofnoncompliance;
  ppp_typeofnoncompliance7: ppp_typeofnoncompliance;
  ppp_typeofnoncompliance8: ppp_typeofnoncompliance;
  ppp_typeofnoncompliance9: ppp_typeofnoncompliance;
  statecode: ppp_acquittalandcompliance_statecode;
  statuscode: ppp_acquittalandcompliance_statuscode;
  timezoneruleversionnumber: number;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface ppp_AcquittalandCompliance_Expand {
  ppp_SATAReference: WebExpand<ppp_AcquittalandCompliance_Expand, ppp_Traveller_Select, ppp_Traveller_Filter, { ppp_SATAReference: ppp_Traveller_Result }>;
}
interface ppp_AcquittalandCompliance_FormattedResult {
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  ppp_aircarrier_formatted?: string;
  ppp_flightconnection10_formatted?: string;
  ppp_flightconnection1_formatted?: string;
  ppp_flightconnection2_formatted?: string;
  ppp_flightconnection3_formatted?: string;
  ppp_flightconnection4_formatted?: string;
  ppp_flightconnection5_formatted?: string;
  ppp_flightconnection6_formatted?: string;
  ppp_flightconnection7_formatted?: string;
  ppp_flightconnection8_formatted?: string;
  ppp_flightconnection9_formatted?: string;
  ppp_flightdestination_formatted?: string;
  ppp_flightorigin_formatted?: string;
  ppp_flightorigindate_formatted?: string;
  ppp_flightorigintime_formatted?: string;
  ppp_inspectorname_formatted?: string;
  ppp_recordtype_formatted?: string;
  ppp_ruleid10_formatted?: string;
  ppp_ruleid1_formatted?: string;
  ppp_ruleid2_formatted?: string;
  ppp_ruleid3_formatted?: string;
  ppp_ruleid4_formatted?: string;
  ppp_ruleid5_formatted?: string;
  ppp_ruleid6_formatted?: string;
  ppp_ruleid7_formatted?: string;
  ppp_ruleid8_formatted?: string;
  ppp_ruleid9_formatted?: string;
  ppp_satareference_formatted?: string;
  ppp_typeofnoncompliance10_formatted?: string;
  ppp_typeofnoncompliance1_formatted?: string;
  ppp_typeofnoncompliance2_formatted?: string;
  ppp_typeofnoncompliance3_formatted?: string;
  ppp_typeofnoncompliance4_formatted?: string;
  ppp_typeofnoncompliance5_formatted?: string;
  ppp_typeofnoncompliance6_formatted?: string;
  ppp_typeofnoncompliance7_formatted?: string;
  ppp_typeofnoncompliance8_formatted?: string;
  ppp_typeofnoncompliance9_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
}
interface ppp_AcquittalandCompliance_Result extends ppp_AcquittalandCompliance_Base, ppp_AcquittalandCompliance_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  ppp_aircarrier_guid: string | null;
  ppp_flightconnection10_guid: string | null;
  ppp_flightconnection1_guid: string | null;
  ppp_flightconnection2_guid: string | null;
  ppp_flightconnection3_guid: string | null;
  ppp_flightconnection4_guid: string | null;
  ppp_flightconnection5_guid: string | null;
  ppp_flightconnection6_guid: string | null;
  ppp_flightconnection7_guid: string | null;
  ppp_flightconnection8_guid: string | null;
  ppp_flightconnection9_guid: string | null;
  ppp_flightdestination_guid: string | null;
  ppp_flightorigin_guid: string | null;
  ppp_inspectorname_guid: string | null;
  ppp_satareference_guid: string | null;
}
interface ppp_AcquittalandCompliance_RelatedOne {
  ppp_SATAReference: WebMappingRetrieve<ppp_Traveller_Select,ppp_Traveller_Expand,ppp_Traveller_Filter,ppp_Traveller_Fixed,ppp_Traveller_Result,ppp_Traveller_FormattedResult>;
}
interface ppp_AcquittalandCompliance_RelatedMany {
}
interface WebEntitiesRetrieve {
  ppp_acquittalandcompliances: WebMappingRetrieve<ppp_AcquittalandCompliance_Select,ppp_AcquittalandCompliance_Expand,ppp_AcquittalandCompliance_Filter,ppp_AcquittalandCompliance_Fixed,ppp_AcquittalandCompliance_Result,ppp_AcquittalandCompliance_FormattedResult>;
}
interface WebEntitiesRelated {
  ppp_acquittalandcompliances: WebMappingRelated<ppp_AcquittalandCompliance_RelatedOne,ppp_AcquittalandCompliance_RelatedMany>;
}
interface WebEntitiesCUDA {
  ppp_acquittalandcompliances: WebMappingCUDA<ppp_AcquittalandCompliance_Create,ppp_AcquittalandCompliance_Update,ppp_AcquittalandCompliance_Select>;
}
