interface ppp_Traveller_Base extends WebEntity {
  createdon?: Date | null;
  importsequencenumber?: number | null;
  modifiedon?: Date | null;
  overriddencreatedon?: Date | null;
  ppp_baggagecarryon?: number | null;
  ppp_baggagechecked?: number | null;
  ppp_calltype?: ppp_calltype | null;
  ppp_casebriefoptionother?: string | null;
  ppp_casebriefoptions?: ppp_casebriefoptions | null;
  ppp_checkedbaggagetagnumber?: string | null;
  ppp_closeddate?: Date | null;
  ppp_dateofbirth?: Date | null;
  ppp_directionoptionother?: string | null;
  ppp_directionoptions?: ppp_directionoptions | null;
  ppp_directiontime?: Date | null;
  ppp_finalstatustime?: Date | null;
  ppp_firstname?: string | null;
  ppp_flightconnectioncount?: number | null;
  ppp_flightnumber?: string | null;
  ppp_flightorigindate?: Date | null;
  ppp_flightoriginhour?: number | null;
  ppp_flightoriginminute?: number | null;
  ppp_flightorigintime?: Date | null;
  ppp_gender?: ppp_gender | null;
  ppp_iddetails?: string | null;
  ppp_idsused?: ppp_idsused | null;
  ppp_ispresent?: boolean | null;
  ppp_ispresenttime?: Date | null;
  ppp_lastknownaddress?: string | null;
  ppp_lastname?: string | null;
  ppp_lawenforcementagency?: ppp_nominatingagencyadditional | null;
  ppp_lawenforcementnotifieddetails?: string | null;
  ppp_matchfound?: ppp_matchfound | null;
  ppp_matchfoundtime?: Date | null;
  ppp_middlename?: string | null;
  ppp_minuteswaiting?: number | null;
  ppp_name?: string | null;
  ppp_nameprovidedoptions?: ppp_nameprovidedoptions | null;
  ppp_newrecordtime?: Date | null;
  ppp_nominatingagencyadditional?: ppp_nominatingagencyadditional | null;
  ppp_nominatingagencynotes?: string | null;
  ppp_nominatingagencyoptionother?: string | null;
  ppp_nominatingagencyoptions?: ppp_nominatingagencyoptions | null;
  ppp_opensourceadditional?: ppp_opensourceadditional | null;
  ppp_opensourcenotes?: string | null;
  ppp_otherconsiderations?: string | null;
  ppp_otherconsiderationsdropdown?: ppp_otherconsiderationsdropdown | null;
  ppp_paymentmethod?: ppp_paymentmethod | null;
  ppp_questionsfortc?: string | null;
  ppp_recordstatus?: ppp_recordstatus | null;
  ppp_recourseletterprovided?: ppp_nominatingagencyadditional | null;
  ppp_returnflightinfo?: string | null;
  ppp_returnticketdate?: Date | null;
  ppp_sataid?: string | null;
  ppp_seatrequestdetails?: string | null;
  ppp_seatrequestmade?: ppp_seatrequestmade | null;
  ppp_ticketpurchasedate?: Date | null;
  ppp_ticketpurchasemethod?: ppp_ticketpurchasemethod | null;
  ppp_tickettype?: ppp_tickettype | null;
  ppp_travelagencyaddress?: string | null;
  ppp_travelagencycontactname?: string | null;
  ppp_travelagencycontactphonenumber?: string | null;
  ppp_travelagencyname?: string | null;
  ppp_travelcompanionsdetails?: string | null;
  ppp_travelcompanionsnumber?: number | null;
  ppp_travellerautonumber?: string | null;
  ppp_travellerid?: string | null;
  ppp_travelpurpose?: ppp_travelpurpose | null;
  ppp_travelpurposeother?: string | null;
  processid?: string | null;
  stageid?: string | null;
  statecode?: ppp_traveller_statecode | null;
  statuscode?: ppp_traveller_statuscode | null;
  timezoneruleversionnumber?: number | null;
  traversedpath?: string | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface ppp_Traveller_Relationships {
  ppp_Caller_ppp_Traveller?: ppp_Caller_Result[] | null;
  ppp_acquittalandcompliance_SATAReference_ppp_traveller?: ppp_AcquittalandCompliance_Result[] | null;
}
interface ppp_Traveller extends ppp_Traveller_Base, ppp_Traveller_Relationships {
  ownerid_bind$systemusers?: string | null;
  ownerid_bind$teams?: string | null;
  ppp_AirCarrier_bind$ovs_aircarriers?: string | null;
  ppp_Citizenship_bind$tc_countries?: string | null;
  ppp_FlightConnection10_bind$ovs_facilities?: string | null;
  ppp_FlightConnection1_bind$ovs_facilities?: string | null;
  ppp_FlightConnection2_bind$ovs_facilities?: string | null;
  ppp_FlightConnection3_bind$ovs_facilities?: string | null;
  ppp_FlightConnection4_bind$ovs_facilities?: string | null;
  ppp_FlightConnection5_bind$ovs_facilities?: string | null;
  ppp_FlightConnection6_bind$ovs_facilities?: string | null;
  ppp_FlightConnection7_bind$ovs_facilities?: string | null;
  ppp_FlightConnection8_bind$ovs_facilities?: string | null;
  ppp_FlightConnection9_bind$ovs_facilities?: string | null;
  ppp_FlightDestination_bind$ovs_facilities?: string | null;
  ppp_FlightOrigin_bind$ovs_facilities?: string | null;
  ppp_IDCountry_bind$tc_countries?: string | null;
  stageid_bind$processstages?: string | null;
}
interface ppp_Traveller_Create extends ppp_Traveller {
}
interface ppp_Traveller_Update extends ppp_Traveller {
}
interface ppp_Traveller_Select {
  createdby_guid: WebAttribute<ppp_Traveller_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<ppp_Traveller_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<ppp_Traveller_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  importsequencenumber: WebAttribute<ppp_Traveller_Select, { importsequencenumber: number | null }, {  }>;
  modifiedby_guid: WebAttribute<ppp_Traveller_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<ppp_Traveller_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<ppp_Traveller_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  overriddencreatedon: WebAttribute<ppp_Traveller_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<ppp_Traveller_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<ppp_Traveller_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<ppp_Traveller_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<ppp_Traveller_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  ppp_aircarrier_guid: WebAttribute<ppp_Traveller_Select, { ppp_aircarrier_guid: string | null }, { ppp_aircarrier_formatted?: string }>;
  ppp_baggagecarryon: WebAttribute<ppp_Traveller_Select, { ppp_baggagecarryon: number | null }, {  }>;
  ppp_baggagechecked: WebAttribute<ppp_Traveller_Select, { ppp_baggagechecked: number | null }, {  }>;
  ppp_calltype: WebAttribute<ppp_Traveller_Select, { ppp_calltype: ppp_calltype | null }, { ppp_calltype_formatted?: string }>;
  ppp_casebriefoptionother: WebAttribute<ppp_Traveller_Select, { ppp_casebriefoptionother: string | null }, {  }>;
  ppp_casebriefoptions: WebAttribute<ppp_Traveller_Select, { ppp_casebriefoptions: ppp_casebriefoptions | null }, { ppp_casebriefoptions_formatted?: string }>;
  ppp_checkedbaggagetagnumber: WebAttribute<ppp_Traveller_Select, { ppp_checkedbaggagetagnumber: string | null }, {  }>;
  ppp_citizenship_guid: WebAttribute<ppp_Traveller_Select, { ppp_citizenship_guid: string | null }, { ppp_citizenship_formatted?: string }>;
  ppp_closeddate: WebAttribute<ppp_Traveller_Select, { ppp_closeddate: Date | null }, { ppp_closeddate_formatted?: string }>;
  ppp_dateofbirth: WebAttribute<ppp_Traveller_Select, { ppp_dateofbirth: Date | null }, { ppp_dateofbirth_formatted?: string }>;
  ppp_directionoptionother: WebAttribute<ppp_Traveller_Select, { ppp_directionoptionother: string | null }, {  }>;
  ppp_directionoptions: WebAttribute<ppp_Traveller_Select, { ppp_directionoptions: ppp_directionoptions | null }, { ppp_directionoptions_formatted?: string }>;
  ppp_directiontime: WebAttribute<ppp_Traveller_Select, { ppp_directiontime: Date | null }, { ppp_directiontime_formatted?: string }>;
  ppp_finalstatustime: WebAttribute<ppp_Traveller_Select, { ppp_finalstatustime: Date | null }, { ppp_finalstatustime_formatted?: string }>;
  ppp_firstname: WebAttribute<ppp_Traveller_Select, { ppp_firstname: string | null }, {  }>;
  ppp_flightconnection10_guid: WebAttribute<ppp_Traveller_Select, { ppp_flightconnection10_guid: string | null }, { ppp_flightconnection10_formatted?: string }>;
  ppp_flightconnection1_guid: WebAttribute<ppp_Traveller_Select, { ppp_flightconnection1_guid: string | null }, { ppp_flightconnection1_formatted?: string }>;
  ppp_flightconnection2_guid: WebAttribute<ppp_Traveller_Select, { ppp_flightconnection2_guid: string | null }, { ppp_flightconnection2_formatted?: string }>;
  ppp_flightconnection3_guid: WebAttribute<ppp_Traveller_Select, { ppp_flightconnection3_guid: string | null }, { ppp_flightconnection3_formatted?: string }>;
  ppp_flightconnection4_guid: WebAttribute<ppp_Traveller_Select, { ppp_flightconnection4_guid: string | null }, { ppp_flightconnection4_formatted?: string }>;
  ppp_flightconnection5_guid: WebAttribute<ppp_Traveller_Select, { ppp_flightconnection5_guid: string | null }, { ppp_flightconnection5_formatted?: string }>;
  ppp_flightconnection6_guid: WebAttribute<ppp_Traveller_Select, { ppp_flightconnection6_guid: string | null }, { ppp_flightconnection6_formatted?: string }>;
  ppp_flightconnection7_guid: WebAttribute<ppp_Traveller_Select, { ppp_flightconnection7_guid: string | null }, { ppp_flightconnection7_formatted?: string }>;
  ppp_flightconnection8_guid: WebAttribute<ppp_Traveller_Select, { ppp_flightconnection8_guid: string | null }, { ppp_flightconnection8_formatted?: string }>;
  ppp_flightconnection9_guid: WebAttribute<ppp_Traveller_Select, { ppp_flightconnection9_guid: string | null }, { ppp_flightconnection9_formatted?: string }>;
  ppp_flightconnectioncount: WebAttribute<ppp_Traveller_Select, { ppp_flightconnectioncount: number | null }, {  }>;
  ppp_flightdestination_guid: WebAttribute<ppp_Traveller_Select, { ppp_flightdestination_guid: string | null }, { ppp_flightdestination_formatted?: string }>;
  ppp_flightnumber: WebAttribute<ppp_Traveller_Select, { ppp_flightnumber: string | null }, {  }>;
  ppp_flightorigin_guid: WebAttribute<ppp_Traveller_Select, { ppp_flightorigin_guid: string | null }, { ppp_flightorigin_formatted?: string }>;
  ppp_flightorigindate: WebAttribute<ppp_Traveller_Select, { ppp_flightorigindate: Date | null }, { ppp_flightorigindate_formatted?: string }>;
  ppp_flightoriginhour: WebAttribute<ppp_Traveller_Select, { ppp_flightoriginhour: number | null }, {  }>;
  ppp_flightoriginminute: WebAttribute<ppp_Traveller_Select, { ppp_flightoriginminute: number | null }, {  }>;
  ppp_flightorigintime: WebAttribute<ppp_Traveller_Select, { ppp_flightorigintime: Date | null }, { ppp_flightorigintime_formatted?: string }>;
  ppp_gender: WebAttribute<ppp_Traveller_Select, { ppp_gender: ppp_gender | null }, { ppp_gender_formatted?: string }>;
  ppp_idcountry_guid: WebAttribute<ppp_Traveller_Select, { ppp_idcountry_guid: string | null }, { ppp_idcountry_formatted?: string }>;
  ppp_iddetails: WebAttribute<ppp_Traveller_Select, { ppp_iddetails: string | null }, {  }>;
  ppp_idsused: WebAttribute<ppp_Traveller_Select, { ppp_idsused: ppp_idsused | null }, { ppp_idsused_formatted?: string }>;
  ppp_ispresent: WebAttribute<ppp_Traveller_Select, { ppp_ispresent: boolean | null }, {  }>;
  ppp_ispresenttime: WebAttribute<ppp_Traveller_Select, { ppp_ispresenttime: Date | null }, { ppp_ispresenttime_formatted?: string }>;
  ppp_lastknownaddress: WebAttribute<ppp_Traveller_Select, { ppp_lastknownaddress: string | null }, {  }>;
  ppp_lastname: WebAttribute<ppp_Traveller_Select, { ppp_lastname: string | null }, {  }>;
  ppp_lawenforcementagency: WebAttribute<ppp_Traveller_Select, { ppp_lawenforcementagency: ppp_nominatingagencyadditional | null }, { ppp_lawenforcementagency_formatted?: string }>;
  ppp_lawenforcementnotifieddetails: WebAttribute<ppp_Traveller_Select, { ppp_lawenforcementnotifieddetails: string | null }, {  }>;
  ppp_matchfound: WebAttribute<ppp_Traveller_Select, { ppp_matchfound: ppp_matchfound | null }, { ppp_matchfound_formatted?: string }>;
  ppp_matchfoundtime: WebAttribute<ppp_Traveller_Select, { ppp_matchfoundtime: Date | null }, { ppp_matchfoundtime_formatted?: string }>;
  ppp_middlename: WebAttribute<ppp_Traveller_Select, { ppp_middlename: string | null }, {  }>;
  ppp_minuteswaiting: WebAttribute<ppp_Traveller_Select, { ppp_minuteswaiting: number | null }, {  }>;
  ppp_name: WebAttribute<ppp_Traveller_Select, { ppp_name: string | null }, {  }>;
  ppp_nameprovidedoptions: WebAttribute<ppp_Traveller_Select, { ppp_nameprovidedoptions: ppp_nameprovidedoptions | null }, { ppp_nameprovidedoptions_formatted?: string }>;
  ppp_newrecordtime: WebAttribute<ppp_Traveller_Select, { ppp_newrecordtime: Date | null }, { ppp_newrecordtime_formatted?: string }>;
  ppp_nominatingagencyadditional: WebAttribute<ppp_Traveller_Select, { ppp_nominatingagencyadditional: ppp_nominatingagencyadditional | null }, { ppp_nominatingagencyadditional_formatted?: string }>;
  ppp_nominatingagencynotes: WebAttribute<ppp_Traveller_Select, { ppp_nominatingagencynotes: string | null }, {  }>;
  ppp_nominatingagencyoptionother: WebAttribute<ppp_Traveller_Select, { ppp_nominatingagencyoptionother: string | null }, {  }>;
  ppp_nominatingagencyoptions: WebAttribute<ppp_Traveller_Select, { ppp_nominatingagencyoptions: ppp_nominatingagencyoptions | null }, { ppp_nominatingagencyoptions_formatted?: string }>;
  ppp_opensourceadditional: WebAttribute<ppp_Traveller_Select, { ppp_opensourceadditional: ppp_opensourceadditional | null }, { ppp_opensourceadditional_formatted?: string }>;
  ppp_opensourcenotes: WebAttribute<ppp_Traveller_Select, { ppp_opensourcenotes: string | null }, {  }>;
  ppp_otherconsiderations: WebAttribute<ppp_Traveller_Select, { ppp_otherconsiderations: string | null }, {  }>;
  ppp_otherconsiderationsdropdown: WebAttribute<ppp_Traveller_Select, { ppp_otherconsiderationsdropdown: ppp_otherconsiderationsdropdown | null }, { ppp_otherconsiderationsdropdown_formatted?: string }>;
  ppp_paymentmethod: WebAttribute<ppp_Traveller_Select, { ppp_paymentmethod: ppp_paymentmethod | null }, { ppp_paymentmethod_formatted?: string }>;
  ppp_questionsfortc: WebAttribute<ppp_Traveller_Select, { ppp_questionsfortc: string | null }, {  }>;
  ppp_recordstatus: WebAttribute<ppp_Traveller_Select, { ppp_recordstatus: ppp_recordstatus | null }, { ppp_recordstatus_formatted?: string }>;
  ppp_recourseletterprovided: WebAttribute<ppp_Traveller_Select, { ppp_recourseletterprovided: ppp_nominatingagencyadditional | null }, { ppp_recourseletterprovided_formatted?: string }>;
  ppp_returnflightinfo: WebAttribute<ppp_Traveller_Select, { ppp_returnflightinfo: string | null }, {  }>;
  ppp_returnticketdate: WebAttribute<ppp_Traveller_Select, { ppp_returnticketdate: Date | null }, { ppp_returnticketdate_formatted?: string }>;
  ppp_sataid: WebAttribute<ppp_Traveller_Select, { ppp_sataid: string | null }, {  }>;
  ppp_seatrequestdetails: WebAttribute<ppp_Traveller_Select, { ppp_seatrequestdetails: string | null }, {  }>;
  ppp_seatrequestmade: WebAttribute<ppp_Traveller_Select, { ppp_seatrequestmade: ppp_seatrequestmade | null }, { ppp_seatrequestmade_formatted?: string }>;
  ppp_ticketpurchasedate: WebAttribute<ppp_Traveller_Select, { ppp_ticketpurchasedate: Date | null }, { ppp_ticketpurchasedate_formatted?: string }>;
  ppp_ticketpurchasemethod: WebAttribute<ppp_Traveller_Select, { ppp_ticketpurchasemethod: ppp_ticketpurchasemethod | null }, { ppp_ticketpurchasemethod_formatted?: string }>;
  ppp_tickettype: WebAttribute<ppp_Traveller_Select, { ppp_tickettype: ppp_tickettype | null }, { ppp_tickettype_formatted?: string }>;
  ppp_travelagencyaddress: WebAttribute<ppp_Traveller_Select, { ppp_travelagencyaddress: string | null }, {  }>;
  ppp_travelagencycontactname: WebAttribute<ppp_Traveller_Select, { ppp_travelagencycontactname: string | null }, {  }>;
  ppp_travelagencycontactphonenumber: WebAttribute<ppp_Traveller_Select, { ppp_travelagencycontactphonenumber: string | null }, {  }>;
  ppp_travelagencyname: WebAttribute<ppp_Traveller_Select, { ppp_travelagencyname: string | null }, {  }>;
  ppp_travelcompanionsdetails: WebAttribute<ppp_Traveller_Select, { ppp_travelcompanionsdetails: string | null }, {  }>;
  ppp_travelcompanionsnumber: WebAttribute<ppp_Traveller_Select, { ppp_travelcompanionsnumber: number | null }, {  }>;
  ppp_travellerautonumber: WebAttribute<ppp_Traveller_Select, { ppp_travellerautonumber: string | null }, {  }>;
  ppp_travellerid: WebAttribute<ppp_Traveller_Select, { ppp_travellerid: string | null }, {  }>;
  ppp_travelpurpose: WebAttribute<ppp_Traveller_Select, { ppp_travelpurpose: ppp_travelpurpose | null }, { ppp_travelpurpose_formatted?: string }>;
  ppp_travelpurposeother: WebAttribute<ppp_Traveller_Select, { ppp_travelpurposeother: string | null }, {  }>;
  processid: WebAttribute<ppp_Traveller_Select, { processid: string | null }, {  }>;
  stageid: WebAttribute<ppp_Traveller_Select, { stageid: string | null }, {  }>;
  statecode: WebAttribute<ppp_Traveller_Select, { statecode: ppp_traveller_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<ppp_Traveller_Select, { statuscode: ppp_traveller_statuscode | null }, { statuscode_formatted?: string }>;
  timezoneruleversionnumber: WebAttribute<ppp_Traveller_Select, { timezoneruleversionnumber: number | null }, {  }>;
  traversedpath: WebAttribute<ppp_Traveller_Select, { traversedpath: string | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<ppp_Traveller_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<ppp_Traveller_Select, { versionnumber: number | null }, {  }>;
}
interface ppp_Traveller_Filter {
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  importsequencenumber: number;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  ppp_aircarrier_guid: XQW.Guid;
  ppp_baggagecarryon: number;
  ppp_baggagechecked: number;
  ppp_calltype: ppp_calltype;
  ppp_casebriefoptionother: string;
  ppp_casebriefoptions: ppp_casebriefoptions;
  ppp_checkedbaggagetagnumber: string;
  ppp_citizenship_guid: XQW.Guid;
  ppp_closeddate: Date;
  ppp_dateofbirth: Date;
  ppp_directionoptionother: string;
  ppp_directionoptions: ppp_directionoptions;
  ppp_directiontime: Date;
  ppp_finalstatustime: Date;
  ppp_firstname: string;
  ppp_flightconnection10_guid: XQW.Guid;
  ppp_flightconnection1_guid: XQW.Guid;
  ppp_flightconnection2_guid: XQW.Guid;
  ppp_flightconnection3_guid: XQW.Guid;
  ppp_flightconnection4_guid: XQW.Guid;
  ppp_flightconnection5_guid: XQW.Guid;
  ppp_flightconnection6_guid: XQW.Guid;
  ppp_flightconnection7_guid: XQW.Guid;
  ppp_flightconnection8_guid: XQW.Guid;
  ppp_flightconnection9_guid: XQW.Guid;
  ppp_flightconnectioncount: number;
  ppp_flightdestination_guid: XQW.Guid;
  ppp_flightnumber: string;
  ppp_flightorigin_guid: XQW.Guid;
  ppp_flightorigindate: Date;
  ppp_flightoriginhour: number;
  ppp_flightoriginminute: number;
  ppp_flightorigintime: Date;
  ppp_gender: ppp_gender;
  ppp_idcountry_guid: XQW.Guid;
  ppp_iddetails: string;
  ppp_idsused: ppp_idsused;
  ppp_ispresent: boolean;
  ppp_ispresenttime: Date;
  ppp_lastknownaddress: string;
  ppp_lastname: string;
  ppp_lawenforcementagency: ppp_nominatingagencyadditional;
  ppp_lawenforcementnotifieddetails: string;
  ppp_matchfound: ppp_matchfound;
  ppp_matchfoundtime: Date;
  ppp_middlename: string;
  ppp_minuteswaiting: number;
  ppp_name: string;
  ppp_nameprovidedoptions: ppp_nameprovidedoptions;
  ppp_newrecordtime: Date;
  ppp_nominatingagencyadditional: ppp_nominatingagencyadditional;
  ppp_nominatingagencynotes: string;
  ppp_nominatingagencyoptionother: string;
  ppp_nominatingagencyoptions: ppp_nominatingagencyoptions;
  ppp_opensourceadditional: ppp_opensourceadditional;
  ppp_opensourcenotes: string;
  ppp_otherconsiderations: string;
  ppp_otherconsiderationsdropdown: ppp_otherconsiderationsdropdown;
  ppp_paymentmethod: ppp_paymentmethod;
  ppp_questionsfortc: string;
  ppp_recordstatus: ppp_recordstatus;
  ppp_recourseletterprovided: ppp_nominatingagencyadditional;
  ppp_returnflightinfo: string;
  ppp_returnticketdate: Date;
  ppp_sataid: string;
  ppp_seatrequestdetails: string;
  ppp_seatrequestmade: ppp_seatrequestmade;
  ppp_ticketpurchasedate: Date;
  ppp_ticketpurchasemethod: ppp_ticketpurchasemethod;
  ppp_tickettype: ppp_tickettype;
  ppp_travelagencyaddress: string;
  ppp_travelagencycontactname: string;
  ppp_travelagencycontactphonenumber: string;
  ppp_travelagencyname: string;
  ppp_travelcompanionsdetails: string;
  ppp_travelcompanionsnumber: number;
  ppp_travellerautonumber: string;
  ppp_travellerid: XQW.Guid;
  ppp_travelpurpose: ppp_travelpurpose;
  ppp_travelpurposeother: string;
  processid: XQW.Guid;
  stageid: XQW.Guid;
  statecode: ppp_traveller_statecode;
  statuscode: ppp_traveller_statuscode;
  timezoneruleversionnumber: number;
  traversedpath: string;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface ppp_Traveller_Expand {
  ppp_Caller_ppp_Traveller: WebExpand<ppp_Traveller_Expand, ppp_Caller_Select, ppp_Caller_Filter, { ppp_Caller_ppp_Traveller: ppp_Caller_Result[] }>;
  ppp_acquittalandcompliance_SATAReference_ppp_traveller: WebExpand<ppp_Traveller_Expand, ppp_AcquittalandCompliance_Select, ppp_AcquittalandCompliance_Filter, { ppp_acquittalandcompliance_SATAReference_ppp_traveller: ppp_AcquittalandCompliance_Result[] }>;
}
interface ppp_Traveller_FormattedResult {
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  ppp_aircarrier_formatted?: string;
  ppp_calltype_formatted?: string;
  ppp_casebriefoptions_formatted?: string;
  ppp_citizenship_formatted?: string;
  ppp_closeddate_formatted?: string;
  ppp_dateofbirth_formatted?: string;
  ppp_directionoptions_formatted?: string;
  ppp_directiontime_formatted?: string;
  ppp_finalstatustime_formatted?: string;
  ppp_flightconnection10_formatted?: string;
  ppp_flightconnection1_formatted?: string;
  ppp_flightconnection2_formatted?: string;
  ppp_flightconnection3_formatted?: string;
  ppp_flightconnection4_formatted?: string;
  ppp_flightconnection5_formatted?: string;
  ppp_flightconnection6_formatted?: string;
  ppp_flightconnection7_formatted?: string;
  ppp_flightconnection8_formatted?: string;
  ppp_flightconnection9_formatted?: string;
  ppp_flightdestination_formatted?: string;
  ppp_flightorigin_formatted?: string;
  ppp_flightorigindate_formatted?: string;
  ppp_flightorigintime_formatted?: string;
  ppp_gender_formatted?: string;
  ppp_idcountry_formatted?: string;
  ppp_idsused_formatted?: string;
  ppp_ispresenttime_formatted?: string;
  ppp_lawenforcementagency_formatted?: string;
  ppp_matchfound_formatted?: string;
  ppp_matchfoundtime_formatted?: string;
  ppp_nameprovidedoptions_formatted?: string;
  ppp_newrecordtime_formatted?: string;
  ppp_nominatingagencyadditional_formatted?: string;
  ppp_nominatingagencyoptions_formatted?: string;
  ppp_opensourceadditional_formatted?: string;
  ppp_otherconsiderationsdropdown_formatted?: string;
  ppp_paymentmethod_formatted?: string;
  ppp_recordstatus_formatted?: string;
  ppp_recourseletterprovided_formatted?: string;
  ppp_returnticketdate_formatted?: string;
  ppp_seatrequestmade_formatted?: string;
  ppp_ticketpurchasedate_formatted?: string;
  ppp_ticketpurchasemethod_formatted?: string;
  ppp_tickettype_formatted?: string;
  ppp_travelpurpose_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
}
interface ppp_Traveller_Result extends ppp_Traveller_Base, ppp_Traveller_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  ppp_aircarrier_guid: string | null;
  ppp_citizenship_guid: string | null;
  ppp_flightconnection10_guid: string | null;
  ppp_flightconnection1_guid: string | null;
  ppp_flightconnection2_guid: string | null;
  ppp_flightconnection3_guid: string | null;
  ppp_flightconnection4_guid: string | null;
  ppp_flightconnection5_guid: string | null;
  ppp_flightconnection6_guid: string | null;
  ppp_flightconnection7_guid: string | null;
  ppp_flightconnection8_guid: string | null;
  ppp_flightconnection9_guid: string | null;
  ppp_flightdestination_guid: string | null;
  ppp_flightorigin_guid: string | null;
  ppp_idcountry_guid: string | null;
}
interface ppp_Traveller_RelatedOne {
}
interface ppp_Traveller_RelatedMany {
  ppp_Caller_ppp_Traveller: WebMappingRetrieve<ppp_Caller_Select,ppp_Caller_Expand,ppp_Caller_Filter,ppp_Caller_Fixed,ppp_Caller_Result,ppp_Caller_FormattedResult>;
  ppp_acquittalandcompliance_SATAReference_ppp_traveller: WebMappingRetrieve<ppp_AcquittalandCompliance_Select,ppp_AcquittalandCompliance_Expand,ppp_AcquittalandCompliance_Filter,ppp_AcquittalandCompliance_Fixed,ppp_AcquittalandCompliance_Result,ppp_AcquittalandCompliance_FormattedResult>;
}
interface WebEntitiesRetrieve {
  ppp_travellers: WebMappingRetrieve<ppp_Traveller_Select,ppp_Traveller_Expand,ppp_Traveller_Filter,ppp_Traveller_Fixed,ppp_Traveller_Result,ppp_Traveller_FormattedResult>;
}
interface WebEntitiesRelated {
  ppp_travellers: WebMappingRelated<ppp_Traveller_RelatedOne,ppp_Traveller_RelatedMany>;
}
interface WebEntitiesCUDA {
  ppp_travellers: WebMappingCUDA<ppp_Traveller_Create,ppp_Traveller_Update,ppp_Traveller_Select>;
}
