# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - development
    exclude:
      - releases/old*
      - feature/*-working
  paths:
    include:
      - PassengerProtectProgram/*
    exclude:
      - Plugin/*
      - WebResources/*

pool:
  vmImage: 'vs2017-win2016'

steps:
  - task: PowerPlatformToolInstaller@0
    inputs:
      DefaultVersion: true

  - task: PowerPlatformImportSolution@0
    inputs:
      authenticationType: 'PowerPlatformSPN'
      PowerPlatformSPN: 'ROM QA'
      SolutionInputFile: '$(Build.SourcesDirectory)\PCFControls\DateTwoOptionPCF_1_0_0_1_managed.zip'
      AsyncOperation: true
      MaxAsyncWaitTime: '240'

  - task: PowerPlatformImportSolution@0
    inputs:
      authenticationType: 'PowerPlatformSPN'
      PowerPlatformSPN: 'ROM QA'
      SolutionInputFile: '$(Build.SourcesDirectory)\PCFControls\TimePickerPCF_1_0_0_6_24H_Format.zip'
      AsyncOperation: true
      MaxAsyncWaitTime: '240'
